//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArc.Domain.StoredProcuderModel;
using Microsoft.EntityFrameworkCore;
using System;
[Keyless]
public  class usp_FRAIS_PAIEMENT_T
{
    public int ref_ctr { get; set; }
    public Nullable<decimal> FraisPaiT { get; set; }
}

